/*
 * Copyright (c) 2014 - Copyright holders CIRSFID and Department of
 * Computer Science and Engineering of the University of Bologna
 * 
 * Authors: 
 * Monica Palmirani – CIRSFID of the University of Bologna
 * Fabio Vitali – Department of Computer Science and Engineering of the University of Bologna
 * Luca Cervone – CIRSFID of the University of Bologna
 * 
 * Permission is hereby granted to any person obtaining a copy of this
 * software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 * 
 * The Software can be used by anyone for purposes without commercial gain,
 * including scientific, individual, and charity purposes. If it is used
 * for purposes having commercial gains, an agreement with the copyright
 * holders is required. The above copyright notice and this permission
 * notice shall be included in all copies or substantial portions of the
 * Software.
 * 
 * Except as contained in this notice, the name(s) of the above copyright
 * holders and authors shall not be used in advertising or otherwise to
 * promote the sale, use or other dealings in this Software without prior
 * written authorization.
 * 
 * The end-user documentation included with the redistribution, if any,
 * must include the following acknowledgment: "This product includes
 * software developed by University of Bologna (CIRSFID and Department of
 * Computer Science and Engineering) and its authors (Monica Palmirani, 
 * Fabio Vitali, Luca Cervone)", in the same place and form as other
 * third-party acknowledgments. Alternatively, this acknowledgment may
 * appear in the software itself, in the same form and location as other
 * such third-party acknowledgments.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
 * OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

Ext.define('LIME.Strings', {
    singleton : true,
    
    strings: {
        "en": {
            "error": "Error",
            "languageCode": "en",
            "login": "Login",
            "forgotPassword": "Forgot Password?",
            "fieldIsInvalid": "The value of this field is invalid",
            "guestLogin": "Demo",
            "register": "Register",
            "logoutWarning": "You will lose all the unsaved data. Are you sure you want to logout?",
            "registrationOk": "Registration successful",
            "registrationOkMessage": "Your account has been correctly created.<br/>Please close this window and login.",
            "userWelcome": "Welcome",
            "userOptions": "User options",
            "userLogout": "Logout",
            "userSettings": "Settings",
            "passwordsDontMatch": "Passwords do not match!",
            "semanticError": "Element {name} cannot be inserted here!",
            "patternNotAllowed": "Pattern <b>{elementPattern}</b> is not allowed in the <b>{parentPattern}</b> pattern!",
            "notAllowedMarking": "Not allowed element",
            "markupLanguage": "Markup language",
            "authErrors": {
                "LOGIN_FAILED_TITLE": "Login failed",
                "REGISTRATION_FAILED_TITLE": "Registration failed",
                "ERR_0": "Wrong username or password.<br/>If you are not registered yet please <a class=\"ciao\" href=\"#\">sign up</a>.",
                "ERR_1": "User already exists on the database.",
                "ERR_2": "User could not be created. Please try again in a while or write to admin@admin.com"
            },
            "prefErrors": {
                "GENERIC": "Your preferences could not be retrieved.",
                "PREF_ERR_0": "User's preferences do not exist.",
                "PREF_ERR_1": "Cannot create user's preferences. Try later.",
                "PREF_ERR_2": "Cannot set user's preferences. Try later."
            },
            "internalServerError": "Internal Server Error",
            "uploader": "Uploader",
            "documentName": "Name of the document",
            "selectDocument": "Select document",
            "openDocumentButtonLabel": "Open document",
            "openDocumentButtonTooltip": "Select a document among the ones belonging to you",
            "createDocumentCollectionButtonLabel": "New document collection",
            "createDocumentCollectionButtonTooltip": "Create a new document collection",
            "saveDocumentButtonLabel": "Save",
            "saveDocumentButtonTooltip": "Save the document",
            "saveAsMenuLabel": "Save as...",
            "saveAsMenuTooltip": "Save with a different name/path",
            "eastToolbarTitle": "Document markup",
            "elementsAccordionTitle": "Elements",
            "metadataAccordionTitle": "Metadata",
            "westToolbarTitle": "Outline",
            "documentStructure": "Document structure",
            "commonButtons": "Common elements",
            "openFileWindowMainTitle": "Open document",
            "openFileWindowWestTitle": "Select document",
            "openFileWindowCenterMetaTabTitle": "Metadata",
            "saveFileWindowMainTitle": "Save document",
            "openFileWindowSouthCancelButtonLabel": "Cancel",
            "openFileWindowSouthCancelButtonTooltip": "Cancel the opening of the document",
            "openFileWindowSouthOpenButtonLabel": "Open",
            "openFileWindowSouthOpenButtonTooltip": "Open the selected document",
            "fileMenuButton": "File",
            "documentMenuButton": "Document",
            "editMenuButton": "Edit",
            "preferencesMenuButton": "Preferences",
            "windowMenuButton": "Window",
            "menuShowView": "Show view",
            "menuShowStyle": "Show style",
            "menuShowStyleBox": "Show boxes",
            "menuShowStyleColor": "Show colors",
            "menuShowStylePdf": "Show style",
            "languageSelectionBoxEmptyText": "Select a language...",
            "localeEmptyText": "Select a locale",
            "legalSystemSelectionBoxEmptyText": "Select a legal system",
            "mainEditor": "Document editor",
            "mainPreview": "{language} preview",
            "mainEditorPath": "Path",
            "warning": "Warning",
            "autoMarkupMessage": "This feature is still under development!<br>This feature tries to markup automatically the document.<br><b>Only the following items will be marked:</b><ul><li>Date</li><li>Reference (Italian)</li></ul>",
            "progressBar": {
                "title": "Working...",
                "buildingViews": "Building views",
                "parsingReferences": "Parsing references",
                "parsingDates": "Parsing dates",
                "configurationFiles": "Loading configuration files",
                "restoringSession": "Restoring previous session",
                "openingDocument": "Opening document",
                "loadingDocument": "Loading document",
                "searchingDates": "Searching dates",
                "markingDates": "Marking dates",
                "searchingRefs": "Searching references",
                "markingRefs": "Marking references",
                "loadingDocumentStyles": "Loading document styles"
            },
            "typeNotSupported": "This type of file is not (yet) supported for drag and drop",
            "uploadError": "There was an error while uploading the file.<br/>Please try again.",
            "savedToTpl": "The document <b>{docName}</b> was successfully saved into <b>{docUrl}</b>",
            "saveAs": "Save As...",
            "welcome": "Welcome",
            "continueStr": "Continue",
            "serverFailure": "Server-side failure.<br/>Malformed response.",
            "noPreferences": "Your preferences could not be created.",
            "newDocumentTip": "Create a new document",
            "newDocument": "New document",
            "ok": "Ok",
            "userRegistration": "User registration",
            "nationality": "Nationality",
            "language": "Language",
            "type": "Type",
            "newLabel": "New",
            "countryLabel": "Country",
            "docProponent": "Doc. Proponent",
            "folderLabel": "Folder",
            "docTypeLabel": "Doc. Type",
            "docDateLabel": "Doc. date",
            "docNumberLabel": "Doc. Number",
            "versionLabel": "Version",
            "fileLabel": "File",
            "newManifestation": "New file in this work",
            "newExpression": "New version",
            "newWork": "New work",
            "missingMetaWarning": "Por favor, introduzca los metadatos que falta.",
            "name": "Name",
            "date": "Date",
            "number": "Number",
            "closeTabText": "Close Tab",
            "closeOthersTabsText": "Close Other Tabs",
            "closeAllTabsText": "Close All Tabs",
            "unmark": "Unmark",
            "unmarkElement": "Unmark this element",
            "unmarkElementChildren": "Unmark this element and its children"
        },
        "it": {
            "error": "Errore",
            "languageCode": "it",
            "login": "Accedi",
            "forgotPassword": "Password dimenticata?",
            "fieldIsInvalid": "Il valore inserito in questo campo non è valido",
            "guestLogin": "Demo",
            "register": "Registrati",
            "logoutWarning": "Perderai tutti i dati non salvati. Sei sicuro di voler eseguire il logout?",
            "registrationOk": "Registrazione riuscita",
            "registrationOkMessage": "Il tuo account è stato creato.<br/>Ti preghiamo di chiudere questa finestra ed eseguire il login.",
            "userWelcome": "Benvenuto",
            "userOptions": "Opzioni",
            "userLogout": "Uscita",
            "userSettings": "Mio profilo",
            "passwordsDontMatch": "Le password sono differenti!",
            "semanticError": "L'elemento {name} non può essere inserito qui",
            "patternNotAllowed": "Il pattern <b>{elementPattern}</b> non può essere contenuto in <b>{parentPattern}</b>!",
            "notAllowedMarking": "Marcatura non permessa",
            "markupLanguage": "Markup language",
            "authErrors": {
                "LOGIN_FAILED_TITLE": "Login fallito",
                "REGISTRATION_FAILED_TITLE": "Registrazione fallita",
                "ERR_0": "Username o password errati.<br/><a class=\"ciao\" href=\"#\">Registrati</a> se non hai ancora un account.",
                "ERR_1": "L'utente già esiste nel database.",
                "ERR_2": "Non è stato possibile creare l'utente.<br/>Per favore riprova tra poco o contattaci al seguente indirizzo email:<br/>admin@admin.com"
            },
            "prefErrors": {
                "GENERIC": "Le tue preferenze non possono essere recuperate.",
                "PREF_ERR_0": "Le preferenze dell'utente non esistono",
                "PREF_ERR_1": "Impossibile creare le preferenze. Prova più tardi.",
                "PREF_ERR_2": "Impossibile impostare le preferenze. Prova più tardi."
            },
            "internalServerError": "Errore del server",
            "uploader": "Caricatore",
            "documentName": "Nome del documento",
            "selectDocument": "Seleziona il documento",
            "openDocumentButtonLabel": "Apri documento",
            "openDocumentButtonTooltip": "Scegli un documento da aprire tra quelli disponibili per te",
            "createDocumentCollectionButtonLabel": "Nuova collezione di documenti",
            "createDocumentCollectionButtonTooltip": "Crea una nuova collezione di documenti",
            "saveDocumentButtonLabel": "Salva",
            "saveDocumentButtonTooltip": "Salva il documento",
            "saveAsMenuLabel": "Salva come...",
            "saveAsMenuTooltip": "Salva con un nome/path differente",
            "eastToolbarTitle": "Markup documento",
            "elementsAccordionTitle": "Elementi",
            "metadataAccordionTitle": "Metadata",
            "saveFileWindowMainTitle": "Salva documento",
            "westToolbarTitle": "Traccia Documento",
            "documentStructure": "Struttura del documento",
            "commonButtons": "Elementi comuni",
            "openFileWindowMainTitle": "Apri documento",
            "openFileWindowWestTitle": "Seleziona documento",
            "openFileWindowCenterMetaTabTitle": "Metadati",
            "openFileWindowSouthCancelButtonLabel": "Annulla",
            "openFileWindowSouthCancelButtonTooltip": "Annulla l'apertura del documento",
            "openFileWindowSouthOpenButtonLabel": "Apri",
            "openFileWindowSouthOpenButtonTooltip": "Apri il documento selezionato",
            "fileMenuButton": "File",
            "documentMenuButton": "Documento",
            "editMenuButton": "Marcatura",
            "preferencesMenuButton": "Preferenze",
            "windowMenuButton": "Finestra",
            "menuShowView": "Visualizza vista",
            "menuShowStyle": "Stile",
            "menuShowStyleBox": "Mostra contenitori",
            "menuShowStyleColor": "Mostra colori",
            "menuShowStylePdf": "Mostra tipografia",
            "languageSelectionBoxEmptyText": "Seleziona una lingua...",
            "localeEmptyText": "Seleziona la localizzazione",
            "mainEditor": "Editor documento",
            "mainPreview": "Anteprima {language}",
            "mainEditorPath": "Percorso",
            "warning": "Attenzione",
            "autoMarkupMessage": "Questa funzionalità è ancora in fase di sviluppo!<br>Questa funzionalità cerca di marcare automaticamente l'intero documento.<br><b>Solo i seguenti elementi verranno marcati:</b><ul><li>Date</li><li>Riferimento (Italiano)</li></ul>",
            "progressBar": {
                "title": "Sto lavorando...",
                "buildingViews": "Costruzione delle viste",
                "parsingReferences": "Analisi dei riferimenti",
                "parsingDates": "Analisi delle date",
                "configurationFiles": "Caricamento dei file di configurazione",
                "restoringSession": "Ripristino della sessione precedente",
                "openingDocument": "Apertura del documento",
                "loadingDocument": "Caricamento del documento",
                "searchingDates": "Ricerca delle date",
                "markingDates": "Marcatura delle date",
                "searchingRefs": "Ricerca dei riferimenti",
                "markingRefs": "Marcatura dei riferimenti",
                "loadingDocumentStyles": "Caricamento degli stili"
            },
            "typeNotSupported": "Questo tipo di file non è (ancora) supportato per il drag and drop",
            "uploadError": "Si è verificato un errore durante l'upload.<br/>Riprovare più tardi.",
            "savedToTpl": "Il documento <b>{docName}</b> è stato salvato con successo in <b>{docUrl}</b>",
            "saveAs": "Salva come...",
            "welcome": "Benvenuto",
            "continueStr": "Continua",
            "serverFailure": "Problema del server.<br/>Risposta mal formata.",
            "noPreferences": "E' stato impossibile salvare le tue preferenze.",
            "newDocumentTip": "Crea un nuovo documento",
            "newDocument": "Nuovo documento",
            "ok": "Ok",
            "userRegistration": "Registrazione dell' utente",
            "newLabel": "Crea",
            "countryLabel": "Nazione",
            "docProponent": "Doc. Proponent",
            "folderLabel": "Cartella",
            "docTypeLabel": "Tipo doc.",
            "docDateLabel": "Data doc.",
            "docNumberLabel": "Numero doc.",
            "versionLabel": "Versione",
            "fileLabel": "File",
            "nationality": "Nazionalità",
            "language": "Linguaggio",
            "type": "Tipo",
            "newManifestation": "Nuovo file in questo work",
            "newExpression": "Nuova versione",
            "newWork": "Nuovo work",
            "missingMetaWarning": "Per favore inserire i metadati mancanti.",
            "name": "Nome",
            "date": "Data",
            "number": "Numero",
            "closeTabText": "Chiudi scheda",
            "closeOthersTabsText": "Chiudi le altre schede",
            "closeAllTabsText": "Chiudi tutte le schede",
            "unmark": "Cancella marcatura",
            "unmarkElement": "questo elemento",
            "unmarkElementChildren": "questo elemento e dei suoi figli"
        },
        "es": {
            "error": "Error",
            "languageCode": "es",
            "login": "Login",
            "forgotPassword": "¿Olvidó su contraseña?",
            "fieldIsInvalid": "El valor de este campo no es válido",
            "guestLogin": "Demo",
            "register": "Registrar",
            "logoutWarning": "Perderá todos los datos no guardados. ¿Está seguro que desea cerrar la sesión?",
            "registrationOk": "El registro se ha realizado correctamente",
            "registrationOkMessage": "Tu cuenta se ha creado correctamente. <br/> Por favor, cierre esta ventana e inicie sesión.",
            "userWelcome": "Bienvenido",
            "userOptions": "Opciones de usuario",
            "userLogout": "Salir",
            "userSettings": "Mi Perfil",
            "passwordsDontMatch": "Le contraseña sono diferenciar!",
            "semanticError": "Element {name} no se puede insertar aquí!",
            "patternNotAllowed": "Pattern <b>{elementPattern}</b> is not allowed in the <b>{parentPattern}</b> pattern!",
            "notAllowedMarking": "Not allowed element",
            "markupLanguage": "Markup language",
            "authErrors": {
                "LOGIN_FAILED_TITLE": "Error de acceso",
                "REGISTRATION_FAILED_TITLE": "Error en el registro",
                "ERR_0": "Nombre de usuario o contraseña incorrecta. <br/> Si no está registrado todavía, por favor <a href=\"#\">inscribirse</a>.",
                "ERR_1": "El usuario ya existe en la base de datos.",
                "ERR_2": "El usuario no pudo ser creada. Vuelve a intentarlo en un rato o escribir a admin@admin.com"
            },
            "prefErrors": {
                "GENERIC": "Sus preferencias no pueden ser recuperados.",
                "PREF_ERR_0": "No existen preferencias del usuario.",
                "PREF_ERR_1": "No se puede crear preferencias de usuario. Intente más tarde.",
                "PREF_ERR_2": "No se puede establecer las preferencias del usuario. Intente más tarde."
            },
            "internalServerError": "Error interno del servidor",
            "uploader": "Cargador",
            "documentName": "Nombre del documento",
            "selectDocument": "Seleccione el documento",
            "openDocumentButtonLabel": "Abrir documento",
            "openDocumentButtonTooltip": "Scegli un documento da aprire tra quelli disponibili per te",
            "createDocumentCollectionButtonLabel": "Nueva colección de documentos",
            "createDocumentCollectionButtonTooltip": "Crear una nueva colección de documentos",
            "saveDocumentButtonLabel": "Guardar",
            "saveDocumentButtonTooltip": "Guardar documento",
            "saveAsMenuLabel": "Guardar como...",
            "saveAsMenuTooltip": "Guardar con un nombre / ruta diferente",
            "eastToolbarTitle": "Markup documento",
            "elementsAccordionTitle": "Elementos",
            "metadataAccordionTitle": "Metadatos",
            "saveFileWindowMainTitle": "Guardar documento",
            "westToolbarTitle": "Outline",
            "documentStructure": "Estructura del documento",
            "commonButtons": "Elementos comunes",
            "openFileWindowMainTitle": "Abrir documento",
            "openFileWindowWestTitle": "Seleccionar documento",
            "openFileWindowCenterMetaTabTitle": "Metadatos",
            "openFileWindowSouthCancelButtonLabel": "Cancelar",
            "openFileWindowSouthCancelButtonTooltip": "Cancelar la apertura del documento",
            "openFileWindowSouthOpenButtonLabel": "Abrir",
            "openFileWindowSouthOpenButtonTooltip": "Abrir el documento seleccionado",
            "fileMenuButton": "Archivo",
            "documentMenuButton": "Documento",
            "editMenuButton": "Editar",
            "preferencesMenuButton": "Preferencias",
            "windowMenuButton": "Ventana",
            "menuShowView": "Mostrar vista",
            "menuShowStyle": "Show style",
            "menuShowStyleBox": "Show boxes",
            "menuShowStyleColor": "Show colors",
            "menuShowStylePdf": "Show style",
            "languageSelectionBoxEmptyText": "Seleccione un idioma...",
            "localeEmptyText": "Seleccione una localidad",
            "mainEditor": "Editor documento",
            "mainPreview": "Avance {language}",
            "mainEditorPath": "Ruta",
            "warning": "Advertencia",
            "autoMarkupMessage": "Esta característica se encuentra todavía en fase de desarrollo!<br>Esta función intenta automáticamente marcado el documento.<br><b>Sólo los siguientes artículos serán marcados:</b><ul><li>Fecha</li><li>Referencia (Italiano)</li></ul>",
            "progressBar": {
                "title": "Estoy trabajando...",
                "buildingViews": "Construcción de visitas",
                "parsingReferences": "Analizar referencias",
                "parsingDates": "Analizar fechas",
                "configurationFiles": "Cargando archivos de configuración",
                "restoringSession": "Restaurar sesión anterior",
                "openingDocument": "Apertura documento",
                "loadingDocument": "Cargando documento",
                "searchingDates": "Fechas búsqueda",
                "markingDates": "Marcado de fechas",
                "searchingRefs": "Referencias búsqueda",
                "markingRefs": "Marcado de referencias",
                "loadingDocumentStyles": "Cargando estilos de documentos"
            },
            "typeNotSupported": "Este tipo de archivo no es (todavía) compatible con arrastrar y soltar",
            "uploadError": "Se produjo un error al cargar el archivo. <br/> Inténtelo de nuevo.",
            "savedToTpl": "El documento <b> {docName} </ b> se guardó con éxito en <b> {docUrl}</b>",
            "saveAs": "Guardar como ...",
            "welcome": "Bienvenido",
            "continueStr": "Continuar",
            "serverFailure": "Insuficiencia del lado del servidor. <br/> Respuesta con formato incorrecto.",
            "noPreferences": "Sus preferencias no pudo ser creada.",
            "newDocumentTip": "Crear un nuevo documento",
            "newDocument": "Nuevo documento",
            "ok": "Ok",
            "userRegistration": "Registrar el usuarios",
            "nationality": "Nacionalidad",
            "language": "Idioma",
            "newLabel": "Nuevo",
            "countryLabel": "País",
            "docProponent": "Doc. Proponent",
            "folderLabel": "Carpeta",
            "docTypeLabel": "Tipo doc.",
            "docDateLabel": "Fecha doc.",
            "docNumberLabel": "Número doc.",
            "versionLabel": "Versión",
            "fileLabel": "Archivio",
            "type": "Tipo",
            "newManifestation": "Nuevo archivo de esta obra",
            "newExpression": "Nueva versión",
            "newWork": "Nueva obra",
            "missingMetaWarning": "Por favor, introduzca los metadatos que falta.",
            "name": "Nombre",
            "date": "Data",
            "number": "Numero",
            "closeTabText": "Cerrar pestaña",
            "closeOthersTabsText": "Cerrar las demás pestañas",
            "closeAllTabsText": "Cierra todas las pestañas",
            "unmark": "Unmark",
            "unmarkElement": "Unmark this element",
            "unmarkElementChildren": "Unmark this element and its children"
        },
        "ro": {
            "error": "Eroare",
            "languageCode": "ro",
            "login": "Login",
            "forgotPassword": "Ai uitat parola?",
            "fieldIsInvalid": "Valoarea acestui câmp este invalidă",
            "guestLogin": "Demo",
            "register": "Înregistrare",
            "logoutWarning": "Veți pierde toate datele nesalvate. Ești sigur că vrei să te deconectezi?",
            "registrationOk": "Înregistrarea a avut succes",
            "registrationOkMessage": "Contul dvs. a fost creat corect.<br/>Închide această fereastră și conecteazăte.",
            "userWelcome": "Bine ai venit",
            "userOptions": "Opțiuni utilizator",
            "userLogout": "Ieșire",
            "userSettings": "Profilul meu",
            "passwordsDontMatch": "Parolele nu corespund!",
            "semanticError": "Elementul {name} nu poate fi inserit aici!",
            "markupLanguage": "Markup language",
            "authErrors": {
                "LOGIN_FAILED_TITLE": "Login nereușit",
                "REGISTRATION_FAILED_TITLE": "înregistrarea nu a reușit",
                "ERR_0": "Utilizator sau parolă este greșită.<br/>Dacă nu sunteți încă înregistrat <a class=\"ciao\" href=\"#\">înregistrează-te</a>.",
                "ERR_1": "Utilizatorul există deja.",
                "ERR_2": "Utilizatorul nu a putut fi creat. Încearcă din nou sau scrie la admin@admin.com"
            },
            "prefErrors": {
                "GENERIC": "Preferințele nu au putut fi recuperate.",
                "PREF_ERR_0": "Preferințele utilizatorului nu există.",
                "PREF_ERR_1": "Nu se pot crea preferințele utilizatorului. Încercă mai târziu.",
                "PREF_ERR_2": "Nu se pot seta preferințele utilizatorului. Încercă mai târziu."
            },
            "internalServerError": "Eroare internă de server",
            "uploader": "Încărcator",
            "documentName": "Numele documentului",
            "selectDocument": "Selectează un document",
            "openDocumentButtonLabel": "Deschide un document",
            "openDocumentButtonTooltip": "Alege un document disponibil pentru tine",
            "saveDocumentButtonLabel": "Salvează",
            "saveDocumentButtonTooltip": "Salvează documentul",
            "saveAsMenuLabel": "Salvare ca...",
            "saveAsMenuTooltip": "Salvează cu un nume diferit",
            "eastToolbarTitle": "Marcarea documentului",
            "elementsAccordionTitle": "Elementele",
            "metadataAccordionTitle": "Metadatele",
            "saveFileWindowMainTitle": "Salvarea documentului",
            "westToolbarTitle": "Conspect",
            "documentStructure": "Structura documentului",
            "commonButtons": "Elemente comune",
            "openFileWindowMainTitle": "Deschide un document",
            "openFileWindowWestTitle": "Selectează un document",
            "openFileWindowCenterMetaTabTitle": "Metadatele",
            "openFileWindowSouthCancelButtonLabel": "Anulează",
            "openFileWindowSouthCancelButtonTooltip": "Anulează deschiderea documentului",
            "openFileWindowSouthOpenButtonLabel": "Deschide",
            "openFileWindowSouthOpenButtonTooltip": "Deschide documentul selecţionat",
            "fileMenuButton": "Fișier",
            "documentMenuButton": "Document",
            "editMenuButton": "Edita",
            "preferencesMenuButton": "Preferințe",
            "windowMenuButton": "Fereastră",
            "menuShowView": "Arată vizionarea",
            "menuShowStyle": "Show style",
            "menuShowStyleBox": "Show boxes",
            "menuShowStyleColor": "Show colors",
            "menuShowStylePdf": "Show style",
            "languageSelectionBoxEmptyText": "Alege o limbă...",
            "localeEmptyText": "Selectați setarea regională",
            "mainEditor": "Editor",
            "mainPreview": "Previzualizare {language}",
            "mainEditorPath": "Cale",
            "warning": "Atenție",
            "autoMarkupMessage": "Această caracteristică este încă în curs de dezvoltare!<br>Încearcă marcajul automat documentului.<br><b>Doar elementele aceste elemente vor fi marcate:</b><ul><li>Data</li><li>Legăturile (Italiană)</li></ul>",
            "progressBar": {
                "title": "Lucrez...",
                "buildingViews": "Construcția vizualizărilor",
                "parsingReferences": "Analizarea referințelor",
                "parsingDates": "Analizarea datelor",
                "configurationFiles": "Încărcarea fișierelor de configurare",
                "restoringSession": "Restabilirea sesiunii precedente",
                "openingDocument": "Deschiderea documentului",
                "loadingDocument": "Încărcarea documentului",
                "searchingDates": "Cautarea datelor",
                "markingDates": "Marcarea datelor",
                "searchingRefs": "Cautarea referințelor",
                "markingRefs": "Marcarea referințelor",
                "loadingDocumentStyles": "Loading document styles"
            },
            "typeNotSupported": "Acest tip de fișier nu este (încă) suportat de drag and drop",
            "uploadError": "A fost o eroare la încărcarea fișierului.<br/>Încercă mai târziu.",
            "savedToTpl": "Documentul <b>{docName}</b> a fost salvat cu succes <b>{docUrl}</b>",
            "saveAs": "Salvare ca...",
            "welcome": "Bun venit!",
            "continueStr": "Continuă",
            "serverFailure": "Eroare internă de server.<br/>Răspuns malformat.",
            "noPreferences": "Preferințele nu au putut fi recuperate.",
            "newDocumentTip": "Crearea noului document",
            "newDocument": "Creeaza un document",
            "ok": "Ok",
            "userRegistration": "Înregistrarea utilizatorului",
            "nationality": "Naționalitate",
            "language": "Lima",
            "countryLabel": "Country",
            "docProponent": "Doc. Proponent",
            "newLabel": "New",
            "folderLabel": "Folder",
            "docTypeLabel": "Doc. Type",
            "docDateLabel": "Doc. date",
            "docNumberLabel": "Doc. Number",
            "versionLabel": "Version",
            "fileLabel": "File",
            "type": "Tip",
            "newManifestation": "Nou fișier in acest work",
            "newExpression": "Nouă versiune",
            "newWork": "Nou work",
            "missingMetaWarning": "Vă rugăm să introduceți metadate lipsește.",
            "name": "Nume",
            "date": "Data",
            "number": "Numar",
            "closeTabText": "Închide fila",
            "closeOthersTabsText": "Închide celelalte file",
            "closeAllTabsText": "Închide toate filele",
            "unmark": "Unmark",
            "unmarkElement": "Unmark this element",
            "unmarkElementChildren": "Unmark this element and its children"
        },
        "ru": {
            "error": "Ошибка",
            "languageCode": "ru",
            "login": "Логин",
            "forgotPassword": "Забыли пароль?",
            "fieldIsInvalid": "Значение этого поля является недействительным",
            "guestLogin": "Демонстрация",
            "register": "Регистрация",
            "logoutWarning": "Вы потеряете все несохраненные данные. Вы уверены, что хотите выйти?",
            "registrationOk": "Успешная регистрация",
            "registrationOkMessage": "Ваш аккаунт был создан.<br/>Пожалуйста, закройте это окно и войдите в систему.",
            "userWelcome": "Добро пожаловать",
            "userOptions": "Настройки пользователя",
            "userLogout": "Выход",
            "userSettings": "Мой профиль",
            "passwordsDontMatch": "Пароли не совпадают!",
            "semanticError": "Элемент {name} не может быть вставлен здесь!",
            "markupLanguage": "Markup language",
            "authErrors": {
                "LOGIN_FAILED_TITLE": "Войти не удалось",
                "REGISTRATION_FAILED_TITLE": "Регистрация не удалась",
                "ERR_0": "Неверное имя пользователя или пароль.<br/>Если вы еще не зарегистрированы, пожалуйста, <a class=\"ciao\" href=\"#\">зарегистрируйтесь</a>.",
                "ERR_1": "Пользователь уже существует.",
                "ERR_2": "Пользователь не может быть создан. Повторите попытку через некоторое время или пишите на admin@admin.com"
            },
            "prefErrors": {
                "GENERIC": "Ваши настройки не может быть получен.",
                "PREF_ERR_0": "Настройки пользователя не существует.",
                "PREF_ERR_1": "Невозможно создать настройки пользователя. Попробуйте позже.",
                "PREF_ERR_2": "Невозможно назначать настройки пользователя. Попробуйте позже."
            },
            "internalServerError": "Внутренняя ошибка сервера",
            "uploader": "Загрузчик",
            "documentName": "Наименование документа",
            "selectDocument": "Выберите документ",
            "openDocumentButtonLabel": "Открыть документ",
            "openDocumentButtonTooltip": "Открываете доступный для Вас документ",
            "saveDocumentButtonLabel": "Сохранить",
            "saveDocumentButtonTooltip": "Сохранить документ",
            "saveAsMenuLabel": "Сохранить как...",
            "saveAsMenuTooltip": "Сохранить под другим именем",
            "eastToolbarTitle": "Разметка документа",
            "elementsAccordionTitle": "Элементы",
            "metadataAccordionTitle": "Метадата",
            "saveFileWindowMainTitle": "Сохранить документ",
            "westToolbarTitle": "Набросок",
            "documentStructure": "Структура документа",
            "commonButtons": "Общие элементы",
            "openFileWindowMainTitle": "Открыть документ",
            "openFileWindowWestTitle": "Выбор документа",
            "openFileWindowCenterMetaTabTitle": "Метадата",
            "openFileWindowSouthCancelButtonLabel": "Отменить",
            "openFileWindowSouthCancelButtonTooltip": "Отменить открывание документа",
            "openFileWindowSouthOpenButtonLabel": "Открыть",
            "openFileWindowSouthOpenButtonTooltip": "Открыть выбранный документ",
            "fileMenuButton": "Файл",
            "documentMenuButton": "Документ",
            "editMenuButton": "Правка",
            "preferencesMenuButton": "Предпочтений",
            "windowMenuButton": "Окно",
            "menuShowView": "Показать панель",
            "menuShowStyle": "Show style",
            "menuShowStyleBox": "Show boxes",
            "menuShowStyleColor": "Show colors",
            "menuShowStylePdf": "Show style",
            "languageSelectionBoxEmptyText": "Выбрать язык...",
            "localeEmptyText": "Выберите локаль",
            "mainEditor": "Редактор",
            "mainPreview": "{language}",
            "mainPdf": "PDF",
            "mainEditorPath": "Теги",
            "warning": "Предупреждение",
            "autoMarkupMessage": "Эта функция находится в стадии разработки!<br>Эта функция пытается автоматически разметкою документа.<br><b>Только следующие элементы будут маркированы:</b><ul><li>Дата</li><li>Ссылка (Итальянский)</li></ul>",
            "progressBar": {
                "title": "Работаю...",
                "buildingViews": "Строение интерфейса",
                "parsingReferences": "Анализирование ссылок",
                "parsingDates": "Анализирование дат",
                "configurationFiles": "Загрузка файлов конфигурации",
                "restoringSession": "Восстановление предыдущей сессии",
                "openingDocument": "Открытие документа",
                "loadingDocument": "Загрузка документа",
                "searchingDates": "Поиск дат",
                "markingDates": "Разметка дат",
                "searchingRefs": "Поиск ссылок",
                "markingRefs": "Разметка ссылок",
                "loadingDocumentStyles": "Loading document styles"
            },
            "typeNotSupported": "Этот тип файла не поддерживается (пока) для перетаскивания",
            "uploadError": "Был Произошла ошибка при загрузке файла.<br/>Попробуйте позже.",
            "savedToTpl": "Документ <b>{docName}</b> был успешно сохранен в <b>{docUrl}</b>",
            "saveAs": "Сохранить как...",
            "welcome": "Добро пожаловать!",
            "continueStr": "Продолжить",
            "serverFailure": "Внутренняя ошибка сервера.<br/>Искаженной ответ.",
            "noPreferences": "Ваши настройки не может быть получен.",
            "newDocumentTip": "Создайте новый документ",
            "newDocument": "Новый документ",
            "ok": "Ok",
            "userRegistration": "Регистрация пользователя",
            "nationality": "Национальность",
            "language": "Язык",
            "type": "Тип",
            "newLabel": "New",
            "countryLabel": "Country",
            "docProponent": "Doc. Proponent",
            "folderLabel": "Folder",
            "docTypeLabel": "Doc. Type",
            "docDateLabel": "Doc. date",
            "docNumberLabel": "Doc. Number",
            "versionLabel": "Version",
            "fileLabel": "File",
            "newManifestation": "Новый файл в этом \"work\"",
            "newExpression": "Новая версия",
            "newWork": "Новый \"work\"",
            "missingMetaWarning": "Пожалуйста, вставьте недостающие метаданные.",
            "name": "Название",
            "date": "Дата",
            "number": "Номер",
            "closeTabText": "Закрыть вкладку",
            "closeOthersTabsText": "Закрыть другие вкладки",
            "closeAllTabsText": "Закрыть все вкладки",
            "unmark": "Unmark",
            "unmarkElement": "Unmark this element",
            "unmarkElementChildren": "Unmark this element and its children"
        }
    }
});
